[package]
name = "elephant-archive"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
elephant_log = { path = "../logger" }

once_cell.workspace = true
chrono.workspace = true
clap = { version="4.0", features = ["derive"] }
